### ISSUE TITLE
Build is not aborted if an error occurs

### ISSUE THREAD

**Issue by edmorley** [techgaun/heroku-buildpack-subdir-to-root#7]
As found in #5, if an error occurs during the compile of this buildpack, the build continues on regardless rather than failing.

Bash error on exit mode should be enabled to prevent this :-)

See:
http://redsymbol.net/articles/unofficial-bash-strict-mode/

**Comment by techgaun** [comment]
thanks for the info and thanks for putting that in there

**Comment by edmorley** [comment]
@techgaun Ah sorry to clarify, PR #6 only fixes #5, it doesn't fix this issue.

**Comment by techgaun** [comment]
ahh thanks @edmorley I thought I saw the `set -xe` or something. How does https://github.com/techgaun/heroku-buildpack-subdir-to-root/pull/8 look?

**Comment by edmorley** [comment]
No worries! The change in #8 looks great :-)
